# Generated by Django 4.1.7 on 2023-05-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('roll_no', models.IntegerField()),
                ('dob', models.DateField()),
                ('marks_percentage', models.IntegerField()),
                ('class_group', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
            ],
        ),
    ]
